/*
Copyright 2026 The Kubernetes Authors

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

// AuthConfigApplyConfiguration represents a declarative configuration of the AuthConfig type for use
// with apply.
//
// AuthConfig configures authentication for the MCP server. At least one
// of tokenProjection or handshakeToken must be specified.
type AuthConfigApplyConfiguration struct {
	// TokenProjection configures ServiceAccount token projection with a
	// custom audience for workload identity federation.
	TokenProjection *TokenProjectionConfigApplyConfiguration `json:"tokenProjection,omitempty"`
	// HandshakeToken configures a bearer token from a Secret for the
	// operator's MCP handshake request.
	HandshakeToken *HandshakeTokenConfigApplyConfiguration `json:"handshakeToken,omitempty"`
}

// AuthConfigApplyConfiguration constructs a declarative configuration of the AuthConfig type for use with
// apply.
func AuthConfig() *AuthConfigApplyConfiguration {
	return &AuthConfigApplyConfiguration{}
}

// WithTokenProjection sets the TokenProjection field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the TokenProjection field is set to the value of the last call.
func (b *AuthConfigApplyConfiguration) WithTokenProjection(value *TokenProjectionConfigApplyConfiguration) *AuthConfigApplyConfiguration {
	b.TokenProjection = value
	return b
}

// WithHandshakeToken sets the HandshakeToken field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the HandshakeToken field is set to the value of the last call.
func (b *AuthConfigApplyConfiguration) WithHandshakeToken(value *HandshakeTokenConfigApplyConfiguration) *AuthConfigApplyConfiguration {
	b.HandshakeToken = value
	return b
}
