/*
Copyright 2026 The Kubernetes Authors

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

// TokenProjectionConfigApplyConfiguration represents a declarative configuration of the TokenProjectionConfig type for use
// with apply.
//
// TokenProjectionConfig configures ServiceAccount token projection with a
// custom audience. The projected token is mounted into the MCP server
// container for workload identity federation.
type TokenProjectionConfigApplyConfiguration struct {
	// Audience is the intended audience of the projected token.
	// Required when tokenProjection is set.
	Audience *string `json:"audience,omitempty"`
	// ExpirationSeconds is the requested duration of validity of the
	// projected token. Defaults to 3600 (1 hour). Must be at least 600
	// (10 minutes) per Kubernetes minimum.
	ExpirationSeconds *int64 `json:"expirationSeconds,omitempty"`
	// MountPath is the container path where the projected token is mounted.
	// Defaults to /var/run/secrets/mcp/token.
	MountPath *string `json:"mountPath,omitempty"`
}

// TokenProjectionConfigApplyConfiguration constructs a declarative configuration of the TokenProjectionConfig type for use with
// apply.
func TokenProjectionConfig() *TokenProjectionConfigApplyConfiguration {
	return &TokenProjectionConfigApplyConfiguration{}
}

// WithAudience sets the Audience field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Audience field is set to the value of the last call.
func (b *TokenProjectionConfigApplyConfiguration) WithAudience(value string) *TokenProjectionConfigApplyConfiguration {
	b.Audience = &value
	return b
}

// WithExpirationSeconds sets the ExpirationSeconds field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ExpirationSeconds field is set to the value of the last call.
func (b *TokenProjectionConfigApplyConfiguration) WithExpirationSeconds(value int64) *TokenProjectionConfigApplyConfiguration {
	b.ExpirationSeconds = &value
	return b
}

// WithMountPath sets the MountPath field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the MountPath field is set to the value of the last call.
func (b *TokenProjectionConfigApplyConfiguration) WithMountPath(value string) *TokenProjectionConfigApplyConfiguration {
	b.MountPath = &value
	return b
}
